name: Libdbc Tests

on:
  push:
    branches: [ "master" ]
  pull_request:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ..

    - name: Build
      run: |
        cd build
        make

    - name: Test
      run: |
        cd build
        ctest --output-on-failure

