name: Libdbc Tests

on:
  push:
    branches: [ "master" ]
  pull_request:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install fast_float dependency
      run: |
        cd ${{github.workspace}}
        git clone https://github.com/fastfloat/fast_float.git
        mkdir fast_float/build
        cd fast_float/build
        cmake -DCMAKE_INSTALL_PREFIX="${{github.workspace}}/installation" ..
        make install

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake -DFastFloat_DIR="${{github.workspace}}/installation/share/cmake/FastFloat" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ..

    - name: Build
      run: |
        cd build
        make

    - name: Test
      run: |
        cd build
        ctest --output-on-failure

