name: Libdbc Tests

on:
  push:
    branches:
      - "master"
  pull_request:
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -Bbuild -H.

    - name: Build the library
      run: |
        cd build
        make -j$(nproc)

    - name: Run unit tests
      run: |
        cd build
        ctest --output-on-failure

  format-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Test format with clang format
      run: ./scripts/fmt.sh

